{
  lib,
  config,
  pkgs,
  ...
}: {
  programs.neovim = {
    # enable = true;
    defaultEditor = true;
    withNodeJs = true;
    withPython3 = true;
    withRuby = true;
    viAlias = true;
    vimAlias = true;
    vimdiffAlias = true;
    # plugins = with pkgs.vimPlugins; [
    #   ollama-nvim
    # ];
    # generatedConfigs = {
    #   viml = ''
    #     " Generated by home-manager
    #     map  ,
    #   '';

    #   lua = ''
    #     -- Generated by home-manager
    #     vim.opt.background = "dark"
    #   '';
    # };
  };
}
