{
  /*
  Legacy window rules (old syntax) kept for reference. The new syntax below
  follows https://wiki.hypr.land/Configuring/Window-Rules/ and uses explicit
  match props with effects.
  */
  # windowrule = [
  #   "float,class:Clockify"
  #   "pin,class:Clockify"
  #   "fullscreen,class:^steam_app_.*$"
  #   "noanim,class:^steam_app_.*$"
  #   "noborder,class:^steam_app_.*$"
  #   "noshadow,class:^steam_app_.*$"
  #   "noblur,class:^steam_app_.*$"
  #   "idleinhibit always,class:^steam_app_.*$"
  #   "idleinhibit fullscreen,class:^duckstation-qt.*$"
  #   "idleinhibit fullscreen,class:^chromium-browser.*$"
  #   "idleinhibit fullscreen,class:^zen.*$"
  #   "idleinhibit always,class:^Ryujinx.*$"
  #   "rounding 4,title:^(Firefox — Sharing Indicator)$"
  #   "noborder,title:^(Firefox — Sharing Indicator)$"
  #   "move 3760 2,title:^(Firefox — Sharing Indicator)$"
  #   "size 76 32,title:^(Firefox — Sharing Indicator)$"
  #   "float,class:(xfce-polkit)"
  #   "noborder,class:(xfce-polkit)"
  #   "float,class:figma-linux,title:Choose directory for export file"
  #   "float,class:(polkit-gnome-authentication-agent-1)"
  #   "noborder,class:(polkit-gnome-authentication-agent-1)"
  #   "noborder,class:(steam)"
  #   "rounding 0,class:(steam)"
  #   "nomaxsize,class:(steam)"
  #   "float,title:^(.*Picture in picture.*)$"
  #   "float,title:^(.*File Operation Progress.*)$"
  #   "pin,title:^(.*Picture in picture.*)$"
  #   "rounding 0,title:^(.*Picture in picture.*)$"
  #   "float,title:^(Firefox — Sharing Indicator)$"
  #   "float,class:(pavucontrol)"
  #   "float,class:(com.nextcloud.desktopclient.nextcloud)"
  #   "nomaxsize,class:(^.*wine.*$)"
  #   "noborder,class:(Xdg-desktop-portal-gtk)"
  #   "noblur,class:(Xdg-desktop-portal-gtk)"
  #   "noshadow,class:(Xdg-desktop-portal-gtk)"
  #   "noanim,class:(Xdg-desktop-portal-gtk)"
  #   "tile,class:(chat-simplex-desktop-MainKt)"
  #   "tile,class:(thunderbird),title:^(.*\\ \\-\\ Mozilla Thunderbird)$"
  #   "float,class:(thunderbird),title:(Edit Event: .*)$"
  #   # Float other Thunderbird dialogs that don't match the main window pattern
  #   "float,class:(thunderbird),title:^(Account Setup|Address Book|Chat|Calendar|Tasks|About Mozilla Thunderbird|Preferences|Settings)"
  #   "tile,class:(1Password),title:^(.*\\ \\-\\ 1Password)$"
  #   # Float 1Password dialogs/popups
  #   "float,class:(1Password),title:^(Quick Access|Unlock|Settings|Preferences)"
  #   "center,class:(1Password),title:^(Quick Access|Unlock|Settings|Preferences)"
  #   "pin,class:1Password,title:1Password"
  #   "center,class:1Password,title:1Password"
  #   "float,class:(python3),title:^(.*Maestral.*)$"
  #   "float,class:(org.onionshare.OnionShare)"
  #   "float,class:(solaar)"
  #   "float,class:polkit-gnome-authentication-agent-1"
  #   "pin,class:polkit-gnome-authentication-agent-1"
  #   "dimaround,class:polkit-gnome-authentication-agent-1"
  #   "float,initialClass:(mpv)"
  #   "pin,initialClass:(mpv)"
  #   "rounding 0,initialClass:(mpv)"
  #   "float,initialClass:(mpv)"
  #   "pin,initialClass:(mpv)"
  #   "rounding 0,initialClass:(mpv)"
  #   "size 768 432,initialClass:(mpv)"
  #   "pin,class:(firefox),title:(Picture-in-Picture)$"
  #   "rounding 0,class:(firefox),title:(Picture-in-Picture)$"
  #   "pin,class:(zen),title:(Picture-in-Picture)$"
  #   "rounding 0,class:(zen),title:(Picture-in-Picture)$"
  #   "float,class:(Ryujinx),title:(ContentDialogOverlayWindow)$"
  #   "noshadow,class:(Ryujinx),title:(ContentDialogOverlayWindow)$"
  #   "noblur,class:(Ryujinx),title:(ContentDialogOverlayWindow)$"
  #   "noborder,class:(Ryujinx),title:(ContentDialogOverlayWindow)$"
  #   "float,class:(firefox),title:(Picture-in-Picture)$"
  #   "float,class:(zen),title:(Picture-in-Picture)$"
  #   "float,class:(thunar),title:(Confirm to replace files)$"
  #   "float,class:^()$,title:(Google Chrome)$"
  #   "stayfocused, title:^()$,class:^(steam)$"
  #   "minsize 1 1, title:^()$,class:^(steam)$"
  #   "float,class:^(firefox)$,title:^(.*Font Finder — Mozilla Firefox)$"
  #   "workspace 6,class:(thunderbird)"
  #   "workspace 5,class:(Slack)"
  #   "workspace 4,class:(ferdium)"
  #   "workspace special:music,class:(Spotify)"
  #   "workspace special:music,class:(rhythmbox)"
  #   "workspace special:music,class:(Plexamp)"
  #   "float,class:(Plexamp)"
  #   "size 1264 890,class:(Plexamp)"
  #   "workspace 5,class:(tidal-hifi)"
  #   "workspace 5,class:(chrome-www.youtube.com__-YouTube)"
  #   "workspace 6,class:^(steam)$,title:(Steam)"
  #   "workspace 6,class:^(heroic)$"
  #   "workspace 9,class:^(FreeTube)$"
  #   "workspace 3,class:figma-linux"
  #   "fullscreen,class:figma-linux"
  #   "workspace 10,class:^steam_app_.*$"
  #   "workspace 10,class:^(hl2_linux)$"
  #   "workspace 10,class:^(hl_linux)$"
  #   "workspace 10,class:^(steam)$,title:(Steam Big Picture Mode)"
  #   "workspace 10,class:^(gamescope)$"
  #   "float,class:^(steam)$,title:^notificationtoasts_"
  #   "pin,class:^(steam)$,title:^notificationtoasts_"
  #   "noborder,class:(com.flipperdevices.qFlipper)"
  #   "noblur,class:(com.flipperdevices.qFlipper)"
  #   "noshadow,class:(com.flipperdevices.qFlipper)"
  #   "noanim,class:(com.flipperdevices.qFlipper)"
  #   "float,class:(com.flipperdevices.qFlipper)"
  #   "float,class:(Upwork)"
  #   "float,class:(com-group_finity-mascot-Main)"
  #   "noblur,class:(com-group_finity-mascot-Main)"
  #   "nofocus,class:(com-group_finity-mascot-Main)"
  #   "noshadow,class:(com-group_finity-mascot-Main)"
  #   "noborder,class:(com-group_finity-mascot-Main)"
  #   "tile,class:(dev.warp.Warp)"
  #   "noborder,class:(dev.warp.Warp)"
  #   "noblur,class:(zoom)"
  #   "rounding 8,class:(zoom)"
  #   "float,class:(zoom),title:(as_toolbar)"
  #   "pin,class:(zoom),title:(as_toolbar)"
  #   "noborder,class:(zoom),title:(as_toolbar)"
  #   "noblur,class:(zoom),title:(as_toolbar)"
  #   "noshadow,class:(zoom),title:(as_toolbar)"
  #   "noanim,class:(zoom),title:(as_toolbar) "
  #   "minsize 816 91,class:(zoom),title:(as_toolbar)"
  #   "maxsize 816 91,class:(zoom),title:(as_toolbar)"
  #   "rounding 0,class:(zoom),title:(as_toolbar)"
  #   "rounding 20,class:(zoom),title:(zoom)"
  #   "noborder,class:(zoom),title:(zoom)"
  #   "float,class:(zoom),title:(zoom_linux_float_video_window)"
  #   "pin,class:(zoom),title:(zoom_linux_float_video_window)"
  #   "noborder,class:(zoom),title:(zoom_linux_float_video_window)"
  #   "noblur,class:(zoom),title:(zoom_linux_float_video_window)"
  #   "noshadow,class:(zoom),title:(zoom_linux_float_video_window)"
  #   "noanim,class:(zoom),title:(zoom_linux_float_video_window)"
  #   "rounding 0,class:(zoom),title:(zoom_linux_float_video_window)"
  #   "float,class:(com.nextcloud.desktopclient.nextcloud)"
  #   "noborder,class:(com.nextcloud.desktopclient.nextcloud)"
  #   "noblur,class:(com.nextcloud.desktopclient.nextcloud)"
  #   "noinitialfocus,class:(com.nextcloud.desktopclient.nextcloud)"
  #   "move onscreen cursor 50% 0%,class:(com.nextcloud.desktopclient.nextcloud)"
  #   "noanim,class:(com.nextcloud.desktopclient.nextcloud)"
  #   "noanim,class:(gamescope)"
  #   "noborder,class:(gamescope)"
  #   "noshadow,class:(gamescope)"
  #   "noblur,class:(gamescope)"
  #   "fullscreen,class:(gamescope)"
  #   "fullscreen,title:(Steam Big Picture Mode)"
  #   "float,class:(yad),title:^(SteamTinkerLaunch-MainMenu)$"
  #   "float,class:(yad),title:^(SteamTinkerLaunch-*)$"
  #   "float,class:(org.speedcrunch.)"
  #   "pin,class:(org.speedcrunch.)"
  #   "float,class:^(nemo)$,title:^(.*\\ Properties)$"
  #   "maxsize 1920 1080,class:(xdg-desktop-portal-gtk)"
  #   "float,class:(xdg-desktop-portal-gtk)"
  #   "pin,class:(xdg-desktop-portal-gtk)"
  #   "dimaround,class:(xdg-desktop-portal-gtk)"
  #   "stayfocused,class:(Rofi)"
  # ];
  windowrule = [
    "match:class Clockify, float"
    "match:class Clockify, pin"
    "match:class ^steam_app_.*$, fullscreen"
    "match:class ^steam_app_.*$, no_anim on"
    "match:class ^steam_app_.*$, border_size 0"
    "match:class ^steam_app_.*$, no_shadow on"
    "match:class ^steam_app_.*$, no_blur on"
    "match:class ^steam_app_.*$, idleinhibit always"
    "match:class ^duckstation-qt.*$, idleinhibit fullscreen"
    "match:class ^chromium-browser.*$, idleinhibit fullscreen"
    "match:class ^zen.*$, idleinhibit fullscreen"
    "match:class ^Ryujinx.*$, idleinhibit always"
    "match:title ^(Firefox — Sharing Indicator)$, rounding 4"
    "match:title ^(Firefox — Sharing Indicator)$, border_size 0"
    "match:title ^(Firefox — Sharing Indicator)$, move 3760 2"
    "match:title ^(Firefox — Sharing Indicator)$, size 76 32"
    "match:class (xfce-polkit), float"
    "match:class (xfce-polkit), border_size 0"
    "match:class figma-linux, match:title ^(Choose directory for export file)$, float"
    "match:class (polkit-gnome-authentication-agent-1), float"
    "match:class (polkit-gnome-authentication-agent-1), border_size 0"
    "match:class (steam), border_size 0"
    "match:class (steam), rounding 0"
    "match:class (steam), maxsize 99999 99999"
    "match:title ^(.*Picture in picture.*)$, float"
    "match:title ^(.*File Operation Progress.*)$, float"
    "match:title ^(.*Picture in picture.*)$, pin"
    "match:title ^(.*Picture in picture.*)$, rounding 0"
    "match:title ^(Firefox — Sharing Indicator)$, float"
    "match:class (pavucontrol), float"
    "match:class (com.nextcloud.desktopclient.nextcloud), float"
    "match:class (^.*wine.*$), maxsize 99999 99999"
    "match:class (Xdg-desktop-portal-gtk), border_size 0"
    "match:class (Xdg-desktop-portal-gtk), no_blur on"
    "match:class (Xdg-desktop-portal-gtk), no_shadow on"
    "match:class (Xdg-desktop-portal-gtk), no_anim on"
    "match:class (chat-simplex-desktop-MainKt), tile"
    "match:class (thunderbird), match:title ^(.* - Mozilla Thunderbird)$, tile"
    "match:class (thunderbird), match:title ^(Edit Event: .*)$, float"
    "match:class (thunderbird), match:title ^(Account Setup|Address Book|Chat|Calendar|Tasks|About Mozilla Thunderbird|Preferences|Settings)$, float"
    "match:class (1Password), match:title ^(.* - 1Password)$, tile"
    "match:class (1Password), match:title ^(Quick Access|Unlock|Settings|Preferences)$, float"
    "match:class (1Password), match:title ^(Quick Access|Unlock|Settings|Preferences)$, center"
    "match:class 1Password, match:title ^1Password$, pin"
    "match:class 1Password, match:title ^1Password$, center"
    "match:class (python3), match:title ^(.*Maestral.*)$, float"
    "match:class (org.onionshare.OnionShare), float"
    "match:class (solaar), float"
    "match:class polkit-gnome-authentication-agent-1, float"
    "match:class polkit-gnome-authentication-agent-1, pin"
    "match:class polkit-gnome-authentication-agent-1, dimaround"
    "match:initial_class (mpv), float"
    "match:initial_class (mpv), pin"
    "match:initial_class (mpv), rounding 0"
    "match:initial_class (mpv), size 768 432"
    "match:class (firefox), match:title ^(Picture-in-Picture)$, pin"
    "match:class (firefox), match:title ^(Picture-in-Picture)$, rounding 0"
    "match:class (zen), match:title ^(Picture-in-Picture)$, pin"
    "match:class (zen), match:title ^(Picture-in-Picture)$, rounding 0"
    "match:class (Ryujinx), match:title ^(ContentDialogOverlayWindow)$, float"
    "match:class (Ryujinx), match:title ^(ContentDialogOverlayWindow)$, no_shadow on"
    "match:class (Ryujinx), match:title ^(ContentDialogOverlayWindow)$, no_blur on"
    "match:class (Ryujinx), match:title ^(ContentDialogOverlayWindow)$, border_size 0"
    "match:class (firefox), match:title ^(Picture-in-Picture)$, float"
    "match:class (zen), match:title ^(Picture-in-Picture)$, float"
    "match:class (thunar), match:title ^(Confirm to replace files)$, float"
    "match:class ^()$, match:title ^(Google Chrome)$, float"
    "match:class ^(steam)$, match:title ^()$, stay_focused on"
    "match:class ^(steam)$, match:title ^()$, minsize 1 1"
    "match:class ^(firefox)$, match:title ^(.*Font Finder — Mozilla Firefox)$, float"
    "match:class (thunderbird), workspace 6"
    "match:class (Slack), workspace 5"
    "match:class (ferdium), workspace 4"
    "match:class (Spotify), workspace special:music"
    "match:class (rhythmbox), workspace special:music"
    "match:class (Plexamp), workspace special:music"
    "match:class (Plexamp), float"
    "match:class (Plexamp), size 1264 890"
    "match:class (tidal-hifi), workspace 5"
    "match:class (chrome-www.youtube.com__-YouTube), workspace 5"
    "match:class ^(steam)$, match:title ^(Steam)$, workspace 6"
    "match:class ^(heroic)$, workspace 6"
    "match:class ^(FreeTube)$, workspace 9"
    "match:class figma-linux, workspace 3"
    "match:class figma-linux, fullscreen"
    "match:class ^steam_app_.*$, workspace 10"
    "match:class ^(hl2_linux)$, workspace 10"
    "match:class ^(hl_linux)$, workspace 10"
    "match:class ^(steam)$, match:title ^(Steam Big Picture Mode)$, workspace 10"
    "match:class ^(gamescope)$, workspace 10"
    "match:class ^(steam)$, match:title ^notificationtoasts_, float"
    "match:class ^(steam)$, match:title ^notificationtoasts_, pin"
    "match:class (com.flipperdevices.qFlipper), border_size 0"
    "match:class (com.flipperdevices.qFlipper), no_blur on"
    "match:class (com.flipperdevices.qFlipper), no_shadow on"
    "match:class (com.flipperdevices.qFlipper), no_anim on"
    "match:class (com.flipperdevices.qFlipper), float"
    "match:class (Upwork), float"
    "match:class (com-group_finity-mascot-Main), float"
    "match:class (com-group_finity-mascot-Main), no_blur on"
    "match:class (com-group_finity-mascot-Main), no_focus on"
    "match:class (com-group_finity-mascot-Main), no_shadow on"
    "match:class (com-group_finity-mascot-Main), border_size 0"
    "match:class (dev.warp.Warp), tile"
    "match:class (dev.warp.Warp), border_size 0"
    "match:class (zoom), no_blur on"
    "match:class (zoom), rounding 8"
    "match:class (zoom), match:title ^(as_toolbar)$, float"
    "match:class (zoom), match:title ^(as_toolbar)$, pin"
    "match:class (zoom), match:title ^(as_toolbar)$, border_size 0"
    "match:class (zoom), match:title ^(as_toolbar)$, no_blur on"
    "match:class (zoom), match:title ^(as_toolbar)$, no_shadow on"
    "match:class (zoom), match:title ^(as_toolbar)$, no_anim on"
    "match:class (zoom), match:title ^(as_toolbar)$, minsize 816 91"
    "match:class (zoom), match:title ^(as_toolbar)$, maxsize 816 91"
    "match:class (zoom), match:title ^(as_toolbar)$, rounding 0"
    "match:class (zoom), match:title ^(zoom)$, rounding 20"
    "match:class (zoom), match:title ^(zoom)$, border_size 0"
    "match:class (zoom), match:title ^(zoom_linux_float_video_window)$, float"
    "match:class (zoom), match:title ^(zoom_linux_float_video_window)$, pin"
    "match:class (zoom), match:title ^(zoom_linux_float_video_window)$, border_size 0"
    "match:class (zoom), match:title ^(zoom_linux_float_video_window)$, no_blur on"
    "match:class (zoom), match:title ^(zoom_linux_float_video_window)$, no_shadow on"
    "match:class (zoom), match:title ^(zoom_linux_float_video_window)$, no_anim on"
    "match:class (zoom), match:title ^(zoom_linux_float_video_window)$, rounding 0"
    "match:class (com.nextcloud.desktopclient.nextcloud), border_size 0"
    "match:class (com.nextcloud.desktopclient.nextcloud), no_blur on"
    "match:class (com.nextcloud.desktopclient.nextcloud), no_initial_focus on"
    "match:class (com.nextcloud.desktopclient.nextcloud), move onscreen cursor 50% 0%"
    "match:class (com.nextcloud.desktopclient.nextcloud), no_anim on"
    "match:class (gamescope), no_anim on"
    "match:class (gamescope), border_size 0"
    "match:class (gamescope), no_shadow on"
    "match:class (gamescope), no_blur on"
    "match:class (gamescope), fullscreen"
    "match:title ^(Steam Big Picture Mode)$, fullscreen"
    "match:class (yad), match:title ^(SteamTinkerLaunch-MainMenu)$, float"
    "match:class (yad), match:title ^SteamTinkerLaunch-.*$, float"
    "match:class (org.speedcrunch.), float"
    "match:class (org.speedcrunch.), pin"
    "match:class ^(nemo)$, match:title ^(.* Properties)$, float"
    "match:class (xdg-desktop-portal-gtk), maxsize 1920 1080"
    "match:class (xdg-desktop-portal-gtk), float"
    "match:class (xdg-desktop-portal-gtk), pin"
    "match:class (xdg-desktop-portal-gtk), dimaround"
    "match:class (Rofi), stay_focused on"
  ];
  # layerrule = ["dimaround,rofi"];
  layerrule = [
    "match:namespace rofi, dimaround"
  ];
}
