# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["vmd" "xhci_pci" "ahci" "nvme" "usbhid" "usb_storage" "sd_mod" "sr_mod"];
  boot.initrd.kernelModules = ["amdgpu" "nfs"];
  boot.kernelModules = ["kvm-intel"];
  boot.extraModulePackages = [];

  boot.kernelParams = [
    "video=DP-1:3840x2160@144"
  ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/d8d94609-cedd-48d3-bb9b-0717b57be9f8";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/EF32-BEF8";
    fsType = "vfat";
    options = ["fmask=0022" "dmask=0022"];
  };

  fileSystems."/NVMe" = {
    device = "/dev/disk/by-uuid/299c7edb-dbed-440b-9c49-16f344520558";
    fsType = "ext4";
    label = "NVMe";
    options = ["defaults" "x-gvfs-show"];
  };

  fileSystems."/SATA" = {
    device = "/dev/disk/by-uuid/85f1737f-a523-4c18-b042-77e4a87404f6";
    fsType = "ext4";
    label = "SATA";
    options = ["defaults" "x-gvfs-show"];
  };

  fileSystems."/mnt/Media" = {
    device = "10.24.24.2:/volume1/Media/";
    fsType = "nfs";
    options = ["defaults" "x-gvfs-show"];
  };

  fileSystems."/mnt/Files" = {
    device = "10.24.24.2:/volume1/Files/";
    fsType = "nfs";
    options = ["defaults" "x-gvfs-show"];
  };

  fileSystems."/mnt/Documents" = {
    device = "10.24.24.2:/volume1/Documents/";
    fsType = "nfs";
    options = ["defaults" "x-gvfs-show"];
  };

  fileSystems."/mnt/Deluge" = {
    device = "10.24.24.2:/volume1/Download/completed/";
    fsType = "nfs";
    options = ["defaults" "x-gvfs-show"];
  };

  fileSystems."/mnt/Camera" = {
    device = "10.24.24.2:/volume1/Camera/";
    fsType = "nfs";
    options = ["defaults" "x-gvfs-show" "x-gvfs-symbolic-icon=camera-symbolic"];
  };

  fileSystems."/mnt/Games" = {
    device = "10.24.24.2:/volume1/Games/";
    fsType = "nfs";
    options = ["defaults" "x-gvfs-show"];
  };

  swapDevices = [
    {device = "/dev/disk/by-uuid/5f7afc03-7b80-41d6-8f6a-ff15d0378b69";}
  ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp6s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp7s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
