{
  windowrule = [
    "match:class Clockify, float on"
    "match:class Clockify, pin on"
    "match:class ^steam_app_.*$, fullscreen on"
    "match:class ^steam_app_.*$, no_anim on"
    "match:class ^steam_app_.*$, border_size 0"
    "match:class ^steam_app_.*$, no_shadow on"
    "match:class ^steam_app_.*$, no_blur on"
    "match:class ^steam_app_.*$, idle_inhibit always"
    "match:class ^duckstation-qt.*$, idle_inhibit fullscreen"
    "match:class ^chromium-browser.*$, idle_inhibit fullscreen"
    "match:class ^zen.*$, idle_inhibit fullscreen"
    "match:class ^Ryujinx.*$, idle_inhibit always"
    "match:title ^(Firefox — Sharing Indicator)$, rounding 4"
    "match:title ^(Firefox — Sharing Indicator)$, border_size 0"
    "match:title ^(Firefox — Sharing Indicator)$, move 3760 2"
    "match:title ^(Firefox — Sharing Indicator)$, size 76 32"
    "match:class (xfce-polkit), float on"
    "match:class (xfce-polkit), border_size 0"
    "match:class figma-linux, match:title ^(Choose directory for export file)$, float on"
    "match:class (polkit-gnome-authentication-agent-1), float on"
    "match:class (polkit-gnome-authentication-agent-1), border_size 0"
    "match:class (steam), border_size 0"
    "match:class (steam), rounding 0"
    "match:class (steam), max_size 99999 99999"
    "match:title ^(.*Picture in picture.*)$, float on"
    "match:title ^(.*File Operation Progress.*)$, float on"
    "match:title ^(.*Picture in picture.*)$, pin on"
    "match:title ^(.*Picture in picture.*)$, rounding 0"
    "match:title ^(Firefox — Sharing Indicator)$, float on"
    "match:class (pavucontrol), float on"
    "match:class (com.nextcloud.desktopclient.nextcloud), float on"
    "match:class (^.*wine.*$), max_size 99999 99999"
    "match:class (Xdg-desktop-portal-gtk), border_size 0"
    "match:class (Xdg-desktop-portal-gtk), no_blur on"
    "match:class (Xdg-desktop-portal-gtk), no_shadow on"
    "match:class (Xdg-desktop-portal-gtk), no_anim on"
    "match:class (chat-simplex-desktop-MainKt), tile on"
    "match:class (thunderbird), match:title ^(.* - Mozilla Thunderbird)$, tile on"
    "match:class (thunderbird), match:title ^(Edit Event: .*)$, float on"
    "match:class (thunderbird), match:title ^(Account Setup|Address Book|Chat|Calendar|Tasks|About Mozilla Thunderbird|Preferences|Settings)$, float on"
    "match:class (1Password), match:title ^(.* - 1Password)$, tile on"
    "match:class (1Password), match:title ^(Quick Access|Unlock|Settings|Preferences)$, float on"
    "match:class (1Password), match:title ^(Quick Access|Unlock|Settings|Preferences)$, center on"
    "match:class 1Password, match:title ^1Password$, pin on"
    "match:class 1Password, match:title ^1Password$, center on"
    "match:class (python3), match:title ^(.*Maestral.*)$, float on"
    "match:class (org.onionshare.OnionShare), float on"
    "match:class (solaar), float on"
    "match:class polkit-gnome-authentication-agent-1, float on"
    "match:class polkit-gnome-authentication-agent-1, pin on"
    "match:class polkit-gnome-authentication-agent-1, dim_around on"
    "match:initial_class (mpv), float on"
    "match:initial_class (mpv), pin on"
    "match:initial_class (mpv), rounding 0"
    "match:initial_class (mpv), size 768 432"
    "match:class (firefox), match:title ^(Picture-in-Picture)$, pin on"
    "match:class (firefox), match:title ^(Picture-in-Picture)$, rounding 0"
    "match:class (zen), match:title ^(Picture-in-Picture)$, pin on"
    "match:class (zen), match:title ^(Picture-in-Picture)$, rounding 0"
    "match:class (Ryujinx), match:title ^(ContentDialogOverlayWindow)$, float on"
    "match:class (Ryujinx), match:title ^(ContentDialogOverlayWindow)$, no_shadow on"
    "match:class (Ryujinx), match:title ^(ContentDialogOverlayWindow)$, no_blur on"
    "match:class (Ryujinx), match:title ^(ContentDialogOverlayWindow)$, border_size 0"
    "match:class (firefox), match:title ^(Picture-in-Picture)$, float on"
    "match:class (zen), match:title ^(Picture-in-Picture)$, float on"
    "match:class (thunar), match:title ^(Confirm to replace files)$, float on"
    "match:class ^()$, match:title ^(Google Chrome)$, float on"
    "match:class ^(steam)$, match:title ^()$, stay_focused on"
    "match:class ^(steam)$, match:title ^()$, min_size 1 1"
    "match:class ^(firefox)$, match:title ^(.*Font Finder — Mozilla Firefox)$, float on"
    "match:class (thunderbird), workspace 6"
    "match:class (Slack), workspace 5"
    "match:class (ferdium), workspace 4"
    "match:class (Spotify), workspace special:music"
    "match:class (rhythmbox), workspace special:music"
    "match:class (Plexamp), workspace special:music"
    "match:class (Plexamp), float on"
    "match:class (Plexamp), size 1264 890"
    "match:class (tidal-hifi), workspace 5"
    "match:class (chrome-www.youtube.com__-YouTube), workspace 5"
    "match:class ^(steam)$, match:title ^(Steam)$, workspace 6"
    "match:class ^(heroic)$, workspace 6"
    "match:class ^(FreeTube)$, workspace 9"
    "match:class figma-linux, workspace 3"
    "match:class figma-linux, fullscreen on"
    "match:class ^steam_app_.*$, workspace 10"
    "match:class ^(hl2_linux)$, workspace 10"
    "match:class ^(hl_linux)$, workspace 10"
    "match:class ^(steam)$, match:title ^(Steam Big Picture Mode)$, workspace 10"
    "match:class ^(gamescope)$, workspace 10"
    "match:class ^(steam)$, match:title ^notificationtoasts_, float on"
    "match:class ^(steam)$, match:title ^notificationtoasts_, pin on"
    "match:class (com.flipperdevices.qFlipper), border_size 0"
    "match:class (com.flipperdevices.qFlipper), no_blur on"
    "match:class (com.flipperdevices.qFlipper), no_shadow on"
    "match:class (com.flipperdevices.qFlipper), no_anim on"
    "match:class (com.flipperdevices.qFlipper), float on"
    "match:class (Upwork), float on"
    "match:class (com-group_finity-mascot-Main), float on"
    "match:class (com-group_finity-mascot-Main), no_blur on"
    "match:class (com-group_finity-mascot-Main), no_focus on"
    "match:class (com-group_finity-mascot-Main), no_shadow on"
    "match:class (com-group_finity-mascot-Main), border_size 0"
    "match:class (dev.warp.Warp), tile on"
    "match:class (dev.warp.Warp), border_size 0"
    "match:class (zoom), no_blur on"
    "match:class (zoom), rounding 8"
    "match:class (zoom), match:title ^(as_toolbar)$, float on"
    "match:class (zoom), match:title ^(as_toolbar)$, pin on"
    "match:class (zoom), match:title ^(as_toolbar)$, border_size 0"
    "match:class (zoom), match:title ^(as_toolbar)$, no_blur on"
    "match:class (zoom), match:title ^(as_toolbar)$, no_shadow on"
    "match:class (zoom), match:title ^(as_toolbar)$, no_anim on"
    "match:class (zoom), match:title ^(as_toolbar)$, min_size 816 91"
    "match:class (zoom), match:title ^(as_toolbar)$, max_size 816 91"
    "match:class (zoom), match:title ^(as_toolbar)$, rounding 0"
    "match:class (zoom), match:title ^(zoom)$, rounding 20"
    "match:class (zoom), match:title ^(zoom)$, border_size 0"
    "match:class (zoom), match:title ^(zoom_linux_float_video_window)$, float on"
    "match:class (zoom), match:title ^(zoom_linux_float_video_window)$, pin on"
    "match:class (zoom), match:title ^(zoom_linux_float_video_window)$, border_size 0"
    "match:class (zoom), match:title ^(zoom_linux_float_video_window)$, no_blur on"
    "match:class (zoom), match:title ^(zoom_linux_float_video_window)$, no_shadow on"
    "match:class (zoom), match:title ^(zoom_linux_float_video_window)$, no_anim on"
    "match:class (zoom), match:title ^(zoom_linux_float_video_window)$, rounding 0"
    "match:class (com.nextcloud.desktopclient.nextcloud), border_size 0"
    "match:class (com.nextcloud.desktopclient.nextcloud), no_blur on"
    "match:class (com.nextcloud.desktopclient.nextcloud), no_initial_focus on"
    "match:class (com.nextcloud.desktopclient.nextcloud), move onscreen cursor 50% 0%"
    "match:class (com.nextcloud.desktopclient.nextcloud), no_anim on"
    "match:class (gamescope), no_anim on"
    "match:class (gamescope), border_size 0"
    "match:class (gamescope), no_shadow on"
    "match:class (gamescope), no_blur on"
    "match:class (gamescope), fullscreen on"
    "match:title ^(Steam Big Picture Mode)$, fullscreen on"
    "match:class (yad), match:title ^(SteamTinkerLaunch-MainMenu)$, float on"
    "match:class (yad), match:title ^SteamTinkerLaunch-.*$, float on"
    "match:class (org.speedcrunch.), float on"
    "match:class (org.speedcrunch.), pin on"
    "match:class ^(nemo)$, match:title ^(.* Properties)$, float on"
    "match:class (xdg-desktop-portal-gtk), max_size 1920 1080"
    "match:class (xdg-desktop-portal-gtk), float on"
    "match:class (xdg-desktop-portal-gtk), pin on"
    "match:class (xdg-desktop-portal-gtk), dim_around on"
    "match:class (Rofi), stay_focused on"
  ];
  # layerrule = ["dim_around,rofi"];
  layerrule = [
    "match:namespace rofi, dim_around on"
  ];
}
